spring:
  application:
    name: logistics
  kafka:
    bootstrap-servers: 'http://localhost:29092'
    consumer:
      group-id: ipurchases-logistics
      auto-offset-reset: earliest

ipurchases:
  config:
    kafka:
      topics:
        pedidos-faturados: 'ipurchases.pedidos-faturados'
        pedidos-enviados: 'ipurchases.pedidos-enviados'

server:
  port: 8084